spring:
  profiles:
    active: local

  datasource:
    url: ${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: ${DB_PASSWORD}

  # 설정들은 spring.io에서 doc에서 찾아서 공부해야한다.
  # jpa설정
  jpa: # hibernate 사용 설정
    show-sql: true
    properties: # property 사용 설정
      hibernate: # hibernate property 설정
        format_sql: true
        dialect: org.hibernate.dialect.MariaDB103Dialect
        database: mariadb
        ddl-auto: none

  redis:
    host: redis
    port: 6379
    password: ${REDIS_PASSWORD}


# 로그 레벨 설정
logging:
  level:
    # hibernate 가 남기는 모든 로그가 debug모드로 설정
    # jpa hibernate가 생성하는 sql이 로거를 통해서 찍히도록 하는 설정
    org.hibernate.SQL: debug
    org.hibernate.type: trace # 실제 들어가는 파라미터값 찍어주는 설정