spring:

  datasource:
    url: jdbc:mariadb://mariadb-1.c1dvuagtpjup.ap-northeast-2.rds.amazonaws.com:3306/test
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: ${DB_PASSWORD}

  # ???? spring.io?? doc?? ??? ??????.
  # jpa??
  jpa: # hibernate ?? ??
    # ?????? ?? ??? ???? ? ???, ?? ?? entity ??? ?? ?? ??? ?? ??
    # if exists drop table ??? ?? ?????? ?? ??.

    show-sql: true
    properties: # property ?? ??
      hibernate: # hibernate property ??
        format_sql: true
        dialect: org.hibernate.dialect.MariaDB103Dialect
        database: mariadb
        ddl-auto: none

# ?? ?? ??
logging:
  level:
    # hibernate ? ??? ?? ??? debug??? ??
    # jpa hibernate? ???? sql? ??? ??? ???? ?? ??
    org.hibernate.SQL: debug
    org.hibernate.type: trace # ?? ???? ????? ???? ??