spring:
  profiles:
    active: dev

  datasource:
    url: ${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: ${DB_PASSWORD}

  # jpa설정
  jpa: # hibernate 사용 설정
    show-sql: true
    properties: # property 사용 설정
      hibernate: # hibernate property 설정
        format_sql: true
        dialect: org.hibernate.dialect.MariaDB103Dialect
        database: mariadb
        ddl-auto: none

  redis:
    port: 6379
    password: ${REDIS_PASSWORD}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_HOST}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000



# 로그 레벨 설정
logging:
  level:
    # hibernate 가 남기는 모든 로그가 debug모드로 설정
    # jpa hibernate가 생성하는 sql이 로거를 통해서 찍히도록 하는 설정
    org.hibernate.SQL: debug
    org.hibernate.type: trace # 실제 들어가는 파라미터값 찍어주는 설정